# Generated by Django 3.2.15 on 2022-08-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_suscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscriptions',
            old_name='TimesUpdated',
            new_name='reactivate',
        ),
    ]
