# Generated by Django 3.2.15 on 2022-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_timesupdated_suscriptions_reactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptions',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
