# Generated by Django 3.2.15 on 2022-09-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptions',
            name='amountTotal',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='suscriptions',
            name='periode',
            field=models.IntegerField(default=None),
        ),
    ]
