# Generated by Django 3.2.15 on 2022-09-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220901_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptions',
            name='plan',
            field=models.CharField(choices=[('basic', '1'), ('standart', '2'), ('premieum', '3'), ('None', '4')], default='None', max_length=20),
        ),
    ]
