# Generated by Django 3.2.15 on 2022-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_suscriptions_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptions',
            name='plan',
            field=models.CharField(choices=[('basic', 'basic'), ('standart', 'standart'), ('premieum', 'premiem'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
