# Generated by Django 3.2.15 on 2022-09-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_suscriptions_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptions',
            name='expired_on',
            field=models.DateTimeField(default=None),
        ),
    ]
