# Generated by Django 3.2.15 on 2022-09-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_suscriptions_expired_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptions',
            name='plan',
            field=models.CharField(choices=[('basic', 'basic'), ('standart', 'standart'), ('premium', 'premium'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
