# Generated by Django 3.2.15 on 2022-09-07 00:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default=None, max_length=200)),
                ('message', models.TextField(default=None)),
                ('views', models.IntegerField(default=None)),
                ('likes', models.IntegerField(default=None)),
                ('success_ratio', models.CharField(default=None, max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
