# Generated by Django 3.2.15 on 2022-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
