# Generated by Django 3.2.15 on 2022-09-19 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_upgradeplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.UUIDField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_article', models.ManyToManyField(default=None, to='dashboard.article')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
