# Generated by Django 3.2.15 on 2022-09-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_save_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_article',
            name='saved_article',
        ),
        migrations.AddField(
            model_name='save_article',
            name='saved_article',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.article'),
        ),
    ]
