# Generated by Django 3.2.15 on 2022-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20220919_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_article',
            name='saved_article',
        ),
        migrations.AddField(
            model_name='save_article',
            name='saved_article',
            field=models.ManyToManyField(default=None, to='dashboard.article'),
        ),
    ]
