# Generated by Django 3.2.15 on 2022-09-10 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btcwallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_address',
            name='btcaddress',
            field=models.CharField(default=None, max_length=250, null=None),
        ),
        migrations.AddField(
            model_name='used_address',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='used_address',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
