# Generated by Django 3.2.15 on 2022-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcwallet', '0002_auto_20220910_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_address',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
